/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Card = IDL.Record({
  'id' : IDL.Nat,
  'front' : IDL.Text,
  'exampleSentence' : IDL.Opt(IDL.Text),
  'starred' : IDL.Bool,
  'back' : IDL.Text,
  'pronunciation' : IDL.Opt(IDL.Text),
  'exampleTranslation' : IDL.Opt(IDL.Text),
  'backImage' : IDL.Opt(ExternalBlob),
  'position' : IDL.Nat,
  'frontImage' : IDL.Opt(ExternalBlob),
  'partOfSpeech' : IDL.Opt(IDL.Text),
});
export const Visibility = IDL.Variant({
  'Private' : IDL.Null,
  'Public' : IDL.Null,
});
export const Deck = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'cardCount' : IDL.Nat,
  'category' : IDL.Text,
  'visibility' : Visibility,
});
export const AccessRequestView = IDL.Record({
  'id' : IDL.Nat,
  'requester' : IDL.Principal,
  'deckId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'requesterName' : IDL.Text,
});
export const StudySession = IDL.Record({
  'mode' : IDL.Text,
  'deckId' : IDL.Nat,
  'cardsStudied' : IDL.Nat,
  'timestamp' : IDL.Int,
  'correctCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'seeded' : IDL.Bool,
});
export const PublicDeckInfo = IDL.Record({
  'title' : IDL.Text,
  'ownerName' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'deckId' : IDL.Nat,
  'cardCount' : IDL.Nat,
  'category' : IDL.Text,
  'likesCount' : IDL.Nat,
  'copyCount' : IDL.Nat,
});
export const GetPublicDecksResult = IDL.Record({
  'total' : IDL.Nat,
  'decks' : IDL.Vec(PublicDeckInfo),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCard' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Card],
      [],
    ),
  'approveAccess' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'bulkAddCards' : IDL.Func(
      [
        IDL.Nat,
        IDL.Vec(
          IDL.Tuple(
            IDL.Text,
            IDL.Text,
            IDL.Opt(IDL.Text),
            IDL.Opt(IDL.Text),
            IDL.Opt(IDL.Text),
            IDL.Opt(IDL.Text),
          )
        ),
      ],
      [IDL.Vec(Card)],
      [],
    ),
  'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createDeck' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Deck], []),
  'deckExists' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'deleteCard' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'deleteDeck' : IDL.Func([IDL.Nat], [], []),
  'duplicateDeck' : IDL.Func([IDL.Nat], [Deck], []),
  'findUserByName' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Principal)], ['query']),
  'getAccessRequests' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AccessRequestView)],
      ['query'],
    ),
  'getCards' : IDL.Func([IDL.Nat], [IDL.Vec(Card)], ['query']),
  'getDeck' : IDL.Func([IDL.Nat], [Deck], ['query']),
  'getDeckSessions' : IDL.Func([IDL.Nat], [IDL.Vec(StudySession)], ['query']),
  'getMyDecks' : IDL.Func([], [IDL.Vec(Deck)], []),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getPublicDeck' : IDL.Func([IDL.Nat], [IDL.Opt(PublicDeckInfo)], ['query']),
  'getPublicDecks' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text, IDL.Nat, IDL.Nat],
      [GetPublicDecksResult],
      ['query'],
    ),
  'getSharedDecks' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'title' : IDL.Text,
            'ownerName' : IDL.Text,
            'description' : IDL.Text,
            'deckId' : IDL.Nat,
            'cardCount' : IDL.Nat,
            'category' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getSharedUsers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Record({ 'principal' : IDL.Principal, 'name' : IDL.Text }))],
      ['query'],
    ),
  'getUserLikes' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'isDeckOwner' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'likeDeck' : IDL.Func([IDL.Nat], [], []),
  'rejectAccess' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'requestDeckAccess' : IDL.Func([IDL.Nat], [], []),
  'saveStudySession' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'setDeckVisibility' : IDL.Func([IDL.Nat, Visibility], [], []),
  'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
  'setProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'shareDeckWith' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'toggleStarCard' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'translateText' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'exampleSentence' : IDL.Text,
            'usageTip' : IDL.Text,
            'translation' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'unlikeDeck' : IDL.Func([IDL.Nat], [], []),
  'unshareDeckWith' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'updateCard' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateCardImages' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateDeck' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [Deck], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Card = IDL.Record({
    'id' : IDL.Nat,
    'front' : IDL.Text,
    'exampleSentence' : IDL.Opt(IDL.Text),
    'starred' : IDL.Bool,
    'back' : IDL.Text,
    'pronunciation' : IDL.Opt(IDL.Text),
    'exampleTranslation' : IDL.Opt(IDL.Text),
    'backImage' : IDL.Opt(ExternalBlob),
    'position' : IDL.Nat,
    'frontImage' : IDL.Opt(ExternalBlob),
    'partOfSpeech' : IDL.Opt(IDL.Text),
  });
  const Visibility = IDL.Variant({ 'Private' : IDL.Null, 'Public' : IDL.Null });
  const Deck = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'cardCount' : IDL.Nat,
    'category' : IDL.Text,
    'visibility' : Visibility,
  });
  const AccessRequestView = IDL.Record({
    'id' : IDL.Nat,
    'requester' : IDL.Principal,
    'deckId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'requesterName' : IDL.Text,
  });
  const StudySession = IDL.Record({
    'mode' : IDL.Text,
    'deckId' : IDL.Nat,
    'cardsStudied' : IDL.Nat,
    'timestamp' : IDL.Int,
    'correctCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'seeded' : IDL.Bool,
  });
  const PublicDeckInfo = IDL.Record({
    'title' : IDL.Text,
    'ownerName' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'deckId' : IDL.Nat,
    'cardCount' : IDL.Nat,
    'category' : IDL.Text,
    'likesCount' : IDL.Nat,
    'copyCount' : IDL.Nat,
  });
  const GetPublicDecksResult = IDL.Record({
    'total' : IDL.Nat,
    'decks' : IDL.Vec(PublicDeckInfo),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCard' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Card],
        [],
      ),
    'approveAccess' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'bulkAddCards' : IDL.Func(
        [
          IDL.Nat,
          IDL.Vec(
            IDL.Tuple(
              IDL.Text,
              IDL.Text,
              IDL.Opt(IDL.Text),
              IDL.Opt(IDL.Text),
              IDL.Opt(IDL.Text),
              IDL.Opt(IDL.Text),
            )
          ),
        ],
        [IDL.Vec(Card)],
        [],
      ),
    'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createDeck' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Deck], []),
    'deckExists' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'deleteCard' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'deleteDeck' : IDL.Func([IDL.Nat], [], []),
    'duplicateDeck' : IDL.Func([IDL.Nat], [Deck], []),
    'findUserByName' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getAccessRequests' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AccessRequestView)],
        ['query'],
      ),
    'getCards' : IDL.Func([IDL.Nat], [IDL.Vec(Card)], ['query']),
    'getDeck' : IDL.Func([IDL.Nat], [Deck], ['query']),
    'getDeckSessions' : IDL.Func([IDL.Nat], [IDL.Vec(StudySession)], ['query']),
    'getMyDecks' : IDL.Func([], [IDL.Vec(Deck)], []),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getPublicDeck' : IDL.Func([IDL.Nat], [IDL.Opt(PublicDeckInfo)], ['query']),
    'getPublicDecks' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text, IDL.Nat, IDL.Nat],
        [GetPublicDecksResult],
        ['query'],
      ),
    'getSharedDecks' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'title' : IDL.Text,
              'ownerName' : IDL.Text,
              'description' : IDL.Text,
              'deckId' : IDL.Nat,
              'cardCount' : IDL.Nat,
              'category' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getSharedUsers' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Vec(
            IDL.Record({ 'principal' : IDL.Principal, 'name' : IDL.Text })
          ),
        ],
        ['query'],
      ),
    'getUserLikes' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'isDeckOwner' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'likeDeck' : IDL.Func([IDL.Nat], [], []),
    'rejectAccess' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'requestDeckAccess' : IDL.Func([IDL.Nat], [], []),
    'saveStudySession' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'setDeckVisibility' : IDL.Func([IDL.Nat, Visibility], [], []),
    'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
    'setProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'shareDeckWith' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'toggleStarCard' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'translateText' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'exampleSentence' : IDL.Text,
              'usageTip' : IDL.Text,
              'translation' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'unlikeDeck' : IDL.Func([IDL.Nat], [], []),
    'unshareDeckWith' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'updateCard' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateCardImages' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateDeck' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Deck],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };