/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessRequestView {
  'id' : bigint,
  'requester' : Principal,
  'deckId' : bigint,
  'timestamp' : bigint,
  'requesterName' : string,
}
export interface Card {
  'id' : bigint,
  'front' : string,
  'exampleSentence' : [] | [string],
  'starred' : boolean,
  'back' : string,
  'pronunciation' : [] | [string],
  'exampleTranslation' : [] | [string],
  'backImage' : [] | [ExternalBlob],
  'position' : bigint,
  'frontImage' : [] | [ExternalBlob],
  'partOfSpeech' : [] | [string],
}
export interface Deck {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'cardCount' : bigint,
  'category' : string,
  'visibility' : Visibility,
}
export type ExternalBlob = Uint8Array;
export interface GetPublicDecksResult {
  'total' : bigint,
  'decks' : Array<PublicDeckInfo>,
}
export interface PublicDeckInfo {
  'title' : string,
  'ownerName' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'deckId' : bigint,
  'cardCount' : bigint,
  'category' : string,
  'likesCount' : bigint,
  'copyCount' : bigint,
}
export interface StudySession {
  'mode' : string,
  'deckId' : bigint,
  'cardsStudied' : bigint,
  'timestamp' : bigint,
  'correctCount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'username' : string,
  'displayName' : string,
  'seeded' : boolean,
}
export type Visibility = { 'Private' : null } |
  { 'Public' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCard' : ActorMethod<
    [
      bigint,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    Card
  >,
  'approveAccess' : ActorMethod<[bigint, Principal], undefined>,
  'bulkAddCards' : ActorMethod<
    [
      bigint,
      Array<
        [
          string,
          string,
          [] | [string],
          [] | [string],
          [] | [string],
          [] | [string],
        ]
      >,
    ],
    Array<Card>
  >,
  'checkUsernameAvailability' : ActorMethod<[string], boolean>,
  'createDeck' : ActorMethod<[string, string, string], Deck>,
  'deckExists' : ActorMethod<[bigint], boolean>,
  'deleteCard' : ActorMethod<[bigint, bigint], undefined>,
  'deleteDeck' : ActorMethod<[bigint], undefined>,
  'duplicateDeck' : ActorMethod<[bigint], Deck>,
  'findUserByName' : ActorMethod<[string], [] | [Principal]>,
  'getAccessRequests' : ActorMethod<[bigint], Array<AccessRequestView>>,
  'getCards' : ActorMethod<[bigint], Array<Card>>,
  'getDeck' : ActorMethod<[bigint], Deck>,
  'getDeckSessions' : ActorMethod<[bigint], Array<StudySession>>,
  'getMyDecks' : ActorMethod<[], Array<Deck>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getPublicDeck' : ActorMethod<[bigint], [] | [PublicDeckInfo]>,
  'getPublicDecks' : ActorMethod<
    [[] | [string], [] | [string], string, bigint, bigint],
    GetPublicDecksResult
  >,
  'getSharedDecks' : ActorMethod<
    [],
    Array<
      {
        'title' : string,
        'ownerName' : string,
        'description' : string,
        'deckId' : bigint,
        'cardCount' : bigint,
        'category' : string,
      }
    >
  >,
  'getSharedUsers' : ActorMethod<
    [bigint],
    Array<{ 'principal' : Principal, 'name' : string }>
  >,
  'getUserLikes' : ActorMethod<[], Array<bigint>>,
  'isDeckOwner' : ActorMethod<[bigint], boolean>,
  'likeDeck' : ActorMethod<[bigint], undefined>,
  'rejectAccess' : ActorMethod<[bigint, Principal], undefined>,
  'requestDeckAccess' : ActorMethod<[bigint], undefined>,
  'saveStudySession' : ActorMethod<[bigint, bigint, bigint, string], undefined>,
  'setDeckVisibility' : ActorMethod<[bigint, Visibility], undefined>,
  'setOpenAIKey' : ActorMethod<[string], undefined>,
  'setProfile' : ActorMethod<[string, string], undefined>,
  'shareDeckWith' : ActorMethod<[bigint, string], undefined>,
  'toggleStarCard' : ActorMethod<[bigint, bigint], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'translateText' : ActorMethod<
    [string],
    {
        'ok' : {
          'exampleSentence' : string,
          'usageTip' : string,
          'translation' : string,
        }
      } |
      { 'err' : string }
  >,
  'unlikeDeck' : ActorMethod<[bigint], undefined>,
  'unshareDeckWith' : ActorMethod<[bigint, Principal], undefined>,
  'updateCard' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updateCardImages' : ActorMethod<
    [bigint, bigint, [] | [ExternalBlob], [] | [ExternalBlob]],
    undefined
  >,
  'updateDeck' : ActorMethod<[bigint, string, string, string], Deck>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];