/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GetPublicDecksResult {
    total: bigint;
    decks: Array<PublicDeckInfo>;
}
export interface Card {
    id: bigint;
    front: string;
    exampleSentence?: string;
    starred: boolean;
    back: string;
    pronunciation?: string;
    exampleTranslation?: string;
    backImage?: ExternalBlob;
    position: bigint;
    frontImage?: ExternalBlob;
    partOfSpeech?: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AccessRequestView {
    id: bigint;
    requester: Principal;
    deckId: bigint;
    timestamp: bigint;
    requesterName: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PublicDeckInfo {
    title: string;
    ownerName: string;
    owner: Principal;
    createdAt: bigint;
    description: string;
    deckId: bigint;
    cardCount: bigint;
    category: string;
    likesCount: bigint;
    copyCount: bigint;
}
export interface StudySession {
    mode: string;
    deckId: bigint;
    cardsStudied: bigint;
    timestamp: bigint;
    correctCount: bigint;
}
export interface Deck {
    id: bigint;
    title: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    cardCount: bigint;
    category: string;
    visibility: Visibility;
}
export interface UserProfile {
    username: string;
    displayName: string;
    seeded: boolean;
}
export enum Visibility {
    Private = "Private",
    Public = "Public"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    addCard(deckId: bigint, front: string, back: string, pronunciation: string | null, partOfSpeech: string | null, exampleSentence: string | null, exampleTranslation: string | null): Promise<Card>;
    approveAccess(deckId: bigint, requester: Principal): Promise<void>;
    bulkAddCards(deckId: bigint, cardPairs: Array<[string, string, string | null, string | null, string | null, string | null]>): Promise<Array<Card>>;
    checkUsernameAvailability(username: string): Promise<boolean>;
    createDeck(title: string, description: string, category: string): Promise<Deck>;
    deckExists(deckId: bigint): Promise<boolean>;
    deleteCard(deckId: bigint, cardId: bigint): Promise<void>;
    deleteDeck(deckId: bigint): Promise<void>;
    duplicateDeck(deckId: bigint): Promise<Deck>;
    findUserByName(username: string): Promise<Principal | null>;
    getAccessRequests(deckId: bigint): Promise<Array<AccessRequestView>>;
    getCards(deckId: bigint): Promise<Array<Card>>;
    getDeck(deckId: bigint): Promise<Deck>;
    getDeckSessions(deckId: bigint): Promise<Array<StudySession>>;
    getMyDecks(): Promise<Array<Deck>>;
    getProfile(): Promise<UserProfile | null>;
    getPublicDeck(deckId: bigint): Promise<PublicDeckInfo | null>;
    getPublicDecks(search: string | null, category: string | null, sort: string, page: bigint, pageSize: bigint): Promise<GetPublicDecksResult>;
    getSharedDecks(): Promise<Array<{
        title: string;
        ownerName: string;
        description: string;
        deckId: bigint;
        cardCount: bigint;
        category: string;
    }>>;
    getSharedUsers(deckId: bigint): Promise<Array<{
        principal: Principal;
        name: string;
    }>>;
    getUserLikes(): Promise<Array<bigint>>;
    isDeckOwner(deckId: bigint): Promise<boolean>;
    likeDeck(deckId: bigint): Promise<void>;
    rejectAccess(deckId: bigint, requester: Principal): Promise<void>;
    requestDeckAccess(deckId: bigint): Promise<void>;
    saveStudySession(deckId: bigint, cardsStudied: bigint, correctCount: bigint, mode: string): Promise<void>;
    setDeckVisibility(deckId: bigint, visibility: Visibility): Promise<void>;
    setOpenAIKey(key: string): Promise<void>;
    setProfile(username: string, displayName: string): Promise<void>;
    shareDeckWith(deckId: bigint, username: string): Promise<void>;
    toggleStarCard(deckId: bigint, cardId: bigint): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    translateText(frenchText: string): Promise<{
        __kind__: "ok";
        ok: {
            exampleSentence: string;
            usageTip: string;
            translation: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    unlikeDeck(deckId: bigint): Promise<void>;
    unshareDeckWith(deckId: bigint, target: Principal): Promise<void>;
    updateCard(deckId: bigint, cardId: bigint, front: string, back: string, pronunciation: string | null, partOfSpeech: string | null, exampleSentence: string | null, exampleTranslation: string | null): Promise<void>;
    updateCardImages(deckId: bigint, cardId: bigint, frontImage: ExternalBlob | null, backImage: ExternalBlob | null): Promise<void>;
    updateDeck(deckId: bigint, title: string, description: string, category: string): Promise<Deck>;
}
import type { Card as _Card, Deck as _Deck, ExternalBlob as _ExternalBlob, PublicDeckInfo as _PublicDeckInfo, UserProfile as _UserProfile, Visibility as _Visibility, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addCard(arg0: bigint, arg1: string, arg2: string, arg3: string | null, arg4: string | null, arg5: string | null, arg6: string | null): Promise<Card> {
        if (this.processError) {
            try {
                const result = await this.actor.addCard(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
                return from_candid_Card_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCard(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
            return from_candid_Card_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveAccess(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveAccess(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveAccess(arg0, arg1);
            return result;
        }
    }
    async bulkAddCards(arg0: bigint, arg1: Array<[string, string, string | null, string | null, string | null, string | null]>): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAddCards(arg0, to_candid_vec_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAddCards(arg0, to_candid_vec_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkUsernameAvailability(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkUsernameAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkUsernameAvailability(arg0);
            return result;
        }
    }
    async createDeck(arg0: string, arg1: string, arg2: string): Promise<Deck> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeck(arg0, arg1, arg2);
                return from_candid_Deck_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeck(arg0, arg1, arg2);
            return from_candid_Deck_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async deckExists(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deckExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deckExists(arg0);
            return result;
        }
    }
    async deleteCard(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCard(arg0, arg1);
            return result;
        }
    }
    async deleteDeck(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDeck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDeck(arg0);
            return result;
        }
    }
    async duplicateDeck(arg0: bigint): Promise<Deck> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateDeck(arg0);
                return from_candid_Deck_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateDeck(arg0);
            return from_candid_Deck_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async findUserByName(arg0: string): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findUserByName(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findUserByName(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAccessRequests(arg0: bigint): Promise<Array<AccessRequestView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccessRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccessRequests(arg0);
            return result;
        }
    }
    async getCards(arg0: bigint): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCards(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCards(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeck(arg0: bigint): Promise<Deck> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeck(arg0);
                return from_candid_Deck_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeck(arg0);
            return from_candid_Deck_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeckSessions(arg0: bigint): Promise<Array<StudySession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeckSessions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeckSessions(arg0);
            return result;
        }
    }
    async getMyDecks(): Promise<Array<Deck>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDecks();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDecks();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicDeck(arg0: bigint): Promise<PublicDeckInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicDeck(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicDeck(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicDecks(arg0: string | null, arg1: string | null, arg2: string, arg3: bigint, arg4: bigint): Promise<GetPublicDecksResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicDecks(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicDecks(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async getSharedDecks(): Promise<Array<{
        title: string;
        ownerName: string;
        description: string;
        deckId: bigint;
        cardCount: bigint;
        category: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedDecks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedDecks();
            return result;
        }
    }
    async getSharedUsers(arg0: bigint): Promise<Array<{
        principal: Principal;
        name: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedUsers(arg0);
            return result;
        }
    }
    async getUserLikes(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLikes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLikes();
            return result;
        }
    }
    async isDeckOwner(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isDeckOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isDeckOwner(arg0);
            return result;
        }
    }
    async likeDeck(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeDeck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeDeck(arg0);
            return result;
        }
    }
    async rejectAccess(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectAccess(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectAccess(arg0, arg1);
            return result;
        }
    }
    async requestDeckAccess(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestDeckAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestDeckAccess(arg0);
            return result;
        }
    }
    async saveStudySession(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStudySession(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStudySession(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setDeckVisibility(arg0: bigint, arg1: Visibility): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDeckVisibility(arg0, to_candid_Visibility_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDeckVisibility(arg0, to_candid_Visibility_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setOpenAIKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOpenAIKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOpenAIKey(arg0);
            return result;
        }
    }
    async setProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0, arg1);
            return result;
        }
    }
    async shareDeckWith(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.shareDeckWith(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shareDeckWith(arg0, arg1);
            return result;
        }
    }
    async toggleStarCard(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleStarCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleStarCard(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async translateText(arg0: string): Promise<{
        __kind__: "ok";
        ok: {
            exampleSentence: string;
            usageTip: string;
            translation: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.translateText(arg0);
                return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.translateText(arg0);
            return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlikeDeck(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeDeck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeDeck(arg0);
            return result;
        }
    }
    async unshareDeckWith(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unshareDeckWith(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unshareDeckWith(arg0, arg1);
            return result;
        }
    }
    async updateCard(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string | null, arg5: string | null, arg6: string | null, arg7: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCard(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCard(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updateCardImages(arg0: bigint, arg1: bigint, arg2: ExternalBlob | null, arg3: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCardImages(arg0, arg1, await to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCardImages(arg0, arg1, await to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateDeck(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<Deck> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeck(arg0, arg1, arg2, arg3);
                return from_candid_Deck_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeck(arg0, arg1, arg2, arg3);
            return from_candid_Deck_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_Card_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Promise<Card> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Deck_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deck): Deck {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Visibility_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Visibility): Visibility {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicDeckInfo]): PublicDeckInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    front: string;
    exampleSentence: [] | [string];
    starred: boolean;
    back: string;
    pronunciation: [] | [string];
    exampleTranslation: [] | [string];
    backImage: [] | [_ExternalBlob];
    position: bigint;
    frontImage: [] | [_ExternalBlob];
    partOfSpeech: [] | [string];
}): Promise<{
    id: bigint;
    front: string;
    exampleSentence?: string;
    starred: boolean;
    back: string;
    pronunciation?: string;
    exampleTranslation?: string;
    backImage?: ExternalBlob;
    position: bigint;
    frontImage?: ExternalBlob;
    partOfSpeech?: string;
}> {
    return {
        id: value.id,
        front: value.front,
        exampleSentence: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.exampleSentence)),
        starred: value.starred,
        back: value.back,
        pronunciation: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.pronunciation)),
        exampleTranslation: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.exampleTranslation)),
        backImage: record_opt_to_undefined(await from_candid_opt_n12(_uploadFile, _downloadFile, value.backImage)),
        position: value.position,
        frontImage: record_opt_to_undefined(await from_candid_opt_n12(_uploadFile, _downloadFile, value.frontImage)),
        partOfSpeech: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.partOfSpeech))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    cardCount: bigint;
    category: string;
    visibility: _Visibility;
}): {
    id: bigint;
    title: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    cardCount: bigint;
    category: string;
    visibility: Visibility;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        cardCount: value.cardCount,
        category: value.category,
        visibility: from_candid_Visibility_n19(_uploadFile, _downloadFile, value.visibility)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Private: null;
} | {
    Public: null;
}): Visibility {
    return "Private" in value ? Visibility.Private : "Public" in value ? Visibility.Public : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        exampleSentence: string;
        usageTip: string;
        translation: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        exampleSentence: string;
        usageTip: string;
        translation: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Card>): Promise<Array<Card>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Card_n9(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Deck>): Array<Deck> {
    return value.map((x)=>from_candid_Deck_n17(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Visibility_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Visibility): _Visibility {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_tuple_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, string, string | null, string | null, string | null, string | null]): [string, string, [] | [string], [] | [string], [] | [string], [] | [string]] {
    return [
        value[0],
        value[1],
        to_candid_opt_n8(_uploadFile, _downloadFile, value[2]),
        to_candid_opt_n8(_uploadFile, _downloadFile, value[3]),
        to_candid_opt_n8(_uploadFile, _downloadFile, value[4]),
        to_candid_opt_n8(_uploadFile, _downloadFile, value[5])
    ];
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Visibility): {
    Private: null;
} | {
    Public: null;
} {
    return value == Visibility.Private ? {
        Private: null
    } : value == Visibility.Public ? {
        Public: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, string, string | null, string | null, string | null, string | null]>): Array<[string, string, [] | [string], [] | [string], [] | [string], [] | [string]]> {
    return value.map((x)=>to_candid_tuple_n15(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
